---
- name: Editar regla de seguridad en Palo Alto
  hosts: firewall_lavi
  connection: local
  gather_facts: no
  tasks:
    - name: Conectar a firewall Palo Alto
      panos_op:
        ip_address: "{{ fw_ip }}"
        username: "{{ fw_username }}"
        password: "{{ fw_password }}"
        cmd: 'show system info'
      register: firewall_info

    - name: Verificar conexión al firewall
      debug:
        var: firewall_info.stdout

    - name: Editar regla de seguridad en el firewall
      panos_security_rule:
        ip_address: "{{ fw_ip }}"
        username: "{{ fw_username }}"
        password: "{{ fw_password }}"
        rule_name: "{{ rule_name }}"
        source_zone: ["untrust"]
        destination_zone: ["trust"]
        source_ip: ["any"]
        destination_ip: ["any"]
        application: ["web-browsing", "ssl"]
        service: ["service-http", "service-https"]
        action: "allow"
        description: "Regla editada por Ansible AWX"
        operation: "update"
      register: rule_update

    - name: Confirmar actualización de la regla
      debug:
        msg: "Regla {{ rule_name }} actualizada correctamente en el firewall {{ fw_ip }}."
