---
- name: Editar una regla de seguridad en Palo Alto
  hosts: "firewall_lavi"
  gather_facts: no
  vars:
    # Variables para el firewall
    rule_name: "Nombre_de_la_Regla" # Nombre de la regla a editar
    action: "allow" # Acción de la regla (allow, deny)
    source_zone: ["trust"] # Zonas de origen
    destination_zone: ["untrust"] # Zonas de destino
    source_address: ["any"]
    destination_address: ["any"]
    application: ["web-browsing"]
    service: ["service-http"]
    description: "Regla modificada por Ansible AWX"
  
  collections:
    - paloaltonetworks.panos
  
  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
  
  
