---
- name: Editar una regla de seguridad en Palo Alto
  hosts: "firewall_lavi"
  connection: local
  gather_facts: no
   
  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    
    # Variables para el firewall
#    rule_name: "testawx" # Nombre de la regla a editar
    action: "allow" # Acción de la regla (allow, deny)
    source_zone: ["any"] # Zonas de origen
    destination_zone: ["any"] # Zonas de destino
    source_ip: ["any"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    service: ["service-http"]
    description: "Regla modificada por Ansible AWX"
   
  collections:
    - paloaltonetworks.panos
  
  tasks:
    - name: Editar la regla de seguridad en el firewall
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "{{ rule_name }}"
        action: "{{ action }}"
        source_zone: "{{ source_zone }}"
        destination_zone: "{{ destination_zone }}"
        source_ip: "{{ source_ip }}"
        destination_ip: "{{ destination_ip }}"
        application: "{{ application }}"
        service: "{{ service }}"
        description: "{{ description }}"
        state: "present"
 
  tasks:
    - name: Mostrar el nombre de la regla editada
      debug:
        msg: "La regla editada fue: {{ rule_name }}"
