---
- name: Actualizar una regla de seguridad en Palo Alto
  hosts: "firewall_lavi"
  gather_facts: no
  connection: local
   
  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    
    # Variables para el firewall
    rule_name: "testawx" # Nombre de la regla a editar
    #action: "allow" # Acción de la regla (allow, deny)
    #source_zone: ["any"] # Zonas de origen
    #destination_zone: ["any"] # Zonas de destino
    nueva_source_ip: ["10.96.144.10"]
    #destination_ip: ["any"]
    #application: ["any"]
    #service: ["service-http"]
    description: "Regla modificada por Ansible AWX1"
   
  collections:
    - paloaltonetworks.panos
  
  tasks:

    - name: Obtener la regla de seguridad actual
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "{{ rule_name }}"
        state: gathered
      register: regla_existente

    - name: Verificar si la IP ya está en la lista de orígenes
      set_fact:
        ip_existe: "{{ nueva_source_ip in (regla_existente.object['source_ip'] | default([])) }}"
        
    - name: Verificar si hay direcciones IP de origen configuradas
      set_fact:
        source_ips: "{{ regla_existente.object['source_ip'] | default([]) }}"
        
#    - name: Mostrar el nombre de las ips existentes:
 #     debug:
  #      msg: "IPs existentes: {{ regla_existente.object['source_ip'] | default([]) }}"

    - name: Agregar la nueva IP a la lista de direcciones de origen de la regla si no existe
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: "{{ rule_name }}"
        source_ip: "{{ (regla_existente.object['source_ip'] | default([])) + nueva_source_ip }}"
        state: present
      when: not ip_existe    
       
#    - name: Editar la regla de seguridad en el firewall
#      paloaltonetworks.panos.panos_security_rule:
#        provider: "{{ device }}"
#        rule_name: "{{ rule_name }}"
        #action: "{{ action }}"
        #source_zone: "{{ source_zone }}"
        #destination_zone: "{{ destination_zone }}"
#        source_ip: "{{ nueva_source_ip }}"
        #destination_ip: "{{ destination_ip }}"
        #application: "{{ application }}"
        #service: "{{ service }}"
        #disabled: "false"
 #       description: "{{ description }}"
 #       state: "present"
 
#  tasks:
#    - name: Mostrar el nombre de la regla editada
#      debug:
#        msg: "La regla editada fue: {{ rule_name }}"
